name: "Pull request check enforcer"

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    name: Check branches
    runs-on: ubuntu-latest

    steps:
      - name: PR summary
        run: |
          echo "PR number: #${{ github.event.number }}"
          echo "Source branch: '${{ github.head_ref }}'"
          echo "Destination branch: '${{ github.base_ref }}'"

      - name: PR rules
        run: |
          if [[ "${{ github.head_ref }}" == 'develop' ]]; then
            echo "Merge from 'develop' to 'main' branch is allowed."
          else
            echo "ERROR: You can only merge to 'main' from a 'develop' branch."
            exit 1
          fi
