name: "Pull request check enforcer"

on:
  pull_request:

jobs:
  check_branch:
    name: Check branches
    runs-on: ubuntu-latest

    steps:
      - name: PR summary
        run: |
          echo "PR number: #${{ github.event.number }}"
          echo "Source branch: '${{ github.head_ref }}'"
          echo "Destination branch: '${{ github.base_ref }}'"

      - name: PR rules
        run: |
          if [[ "${{ github.base_ref }}" == 'main' ]]; then
            if [[ "${{ github.head_ref }}" =~ ^release/ ]]; then
              echo "Merge from 'release/**' to 'main' branch is allowed."
              exit 0
            else
              echo "ERROR: You can only merge to 'main' from a 'release/**' branch."
              exit 1
            fi
          else
            echo "Destination branch is not 'main', merge is allowed."
          fi
