name: .NET Release

on:
  push:
    branches: [ "release/*" ]

jobs:
  publish_nuget:
    uses: ./.github/workflows/dotnet-job-publish-nuget.yaml
    with:
      push_package: true
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY_TEST }}