name: .NET CI

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/dotnet-job-build-test