name: Merge to Develop
run-name: Merge to Develop

on:
    pull_request_target:
      branches: ["develop"]
      types: [closed]

concurrency:
  group: merge-dev-${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true

jobs:
    build_and_test:
      name: Build and Test
      uses: ./.github/workflows/wf-build-test.yaml
  
    update_version:
      name: Update Version
      needs: build_and_test
      permissions:
        contents: write
      uses: ./.github/workflows/wf-update-version.yaml
      with:
        bumpVersion: 0.^.0