name: Continuous Integration
run-name: CI ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - "feature/*"
      - "fix/*"

  pull_request_target:
    branches:
      - "develop"
    types:
      - closed

  push:
    branches:
      - "feature/*"
      - "fix/*"
    paths:
      - "src/**"
      - "tests/**"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/wf-build-test.yaml
