name: Package Release
run-name: Release ${{ github.ref_name }}

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
   
jobs:         
  publish_nuget:
    if: github.event.release.draft == false
    uses: ./.github/workflows/wf-publish-nuget.yaml
    with:
      push_package_to_nuget: ${{ github.event.release.prerelease == false }}
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY_TEST }}
  