name: .NET CI
run-name: Continuous Integration

on:
  pull_request_target:
    branches: ["develop"]
    types: [closed]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true

jobs:
    build_and_test:
      name: Build and Test
      uses: ./.github/workflows/wf-build-test.yaml
  
    update_version:
      name: Update Version
      needs: build_and_test
      uses: ./.github/workflows/wf-update-version.yaml
      permissions:
        contents: write
      with:
        bumpVersion: 0.^.0
        userName: ${{ github.event.pull_request.user.login }}
        userEmail: ${{ github.event.pull_request.user.email }}