name: .NET CI
run-name: Continuous Integration

on:
  push:
    branches: ["feature/*"]
    paths-ignore:
      - "samples/**"
  pull_request_target:
    branches: ["main"]
    types: [closed]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/wf-build-test.yaml

  update_version:
    permissions:
      contents: write
    name: Update Version
    needs: build_and_test
    uses: ./.github/workflows/wf-update-version.yaml
