name: .NET Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    branches: [ "release/*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    
jobs:
  publish_nuget:
    uses: ./.github/workflows/wf-publish-nuget.yaml
    with:
      push_package: true
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY_TEST }}