name: Workflow In Progress
run-name: Workflow In Progress

on:
  workflow_dispatch:
    
  push:
    branches: [ "wip/*" ]

jobs:
    build_and_test:
      uses: ./.github/workflows/dotnet-job-build-test.yaml

    publish_nuget:
      uses: ./.github/workflows/dotnet-job-publish-nuget.yaml
      with:
        push_package: false
        