name: .NET CI
run-name: Continuous Integration

on:
  push:
    branches: ["feature/*"]
    paths-ignore:
      - "samples/**"
      - ".github/workflows/**"
  pull_request_target:
    branches: ["develop"]
    types: [closed]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/wf-build-test.yaml
    with:
      buildConfiguration: "Debug"

  update_version:
    name: Update Version
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
    needs: build_and_test
    uses: ./.github/workflows/wf-update-version.yaml
