name: .NET CI
run-name: Continuous Integration

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]
    types: [synchronize, reopened, closed]

concurrency:
  group: ${{ github.actor_id }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  display:
    name: Build Project & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: group name
        run: echo "group name" ${{ github.actor_id }}-${{ github.workflow }}

  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/wf-build-test.yaml