name: .NET CI
run-name: Continuous Integration

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_test:
    name: Build and Test
    uses: ./.github/workflows/wf-build-test.yaml