name: .NET Build & Test

on:
  workflow_call:

jobs:
  build-project:
    name: Build Project & Test
    runs-on: ubuntu-latest
    env:
      buildConfiguration: Pipeline

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore --configfile NuGetDefaults.config

      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.buildConfiguration }}

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration  ${{ env.buildConfiguration }}