name: 'OpenCommit Action'

on:
  push:
    branches-ignore: [main dev development release feature/*]

jobs:
  opencommit:
    timeout-minutes: 10
    name: OpenCommit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          OCO_OPENAI_API_KEY: ${{ secrets.OCO_OPENAI_API_KEY }}
          OCO_OPENAI_MAX_TOKENS: 500
          OCO_OPENAI_BASE_PATH: ''
          OCO_DESCRIPTION: false
          OCO_EMOJI: false
          OCO_MODEL: gpt-3.5-turbo-0613
          OCO_LANGUAGE: en
          OCO_PROMPT_MODULE: conventional-commit