name: Build and deploy sample app

on:
  push:
    branches:
      - disabled-samples/*
  workflow_dispatch:

env:
  APP_DIR_NAME: sample-app

jobs:
  build:
    name: Build & Publish Trigger App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Samples directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: samples
          sparse-checkout-cone-mode: false

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga

      - name: Build & publish App
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --no-build --property:PublishDir=${{ env.DOTNET_ROOT }}/publish
        working-directory: samples

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_DIR_NAME }}
          path: ${{ env.DOTNET_ROOT }}/publish

  deploy:
    name: Deploy Trigger App
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.APP_DIR_NAME }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.SAMPLE_TRIGGER_APP_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "sample-trigger"
          slot-name: "production"
          package: .
