name: Build and deploy sample apps

on:
  push:
    branches:
      - develop
      - samples/*
  workflow_dispatch:

concurrency:
  group: samples-${{ github.workflow }}-${{ github.actor_id }}
  cancel-in-progress: true

jobs:
  sample-build:
    name: Build & Publish Trigger App
    uses: ./.github/workflows/wf-samples-build.yaml
    with:
      appDirName: ${{ vars.SAMPLE_APP_TRIGGER_NAME }}

  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/wf-tf-plan.yaml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  terraform-apply:
    name: Terraform Apply
    uses: ./.github/workflows/wf-tf-apply.yaml
    needs: terraform-plan
    if: success() && needs.terraform-plan.outputs.tfplanExitCode == 2
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  deploy:
    name: Deploy Trigger App
    runs-on: ubuntu-latest
    needs: [sample-build, terraform-apply]
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.SAMPLE_APP_TRIGGER_NAME }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ${{ vars.SAMPLE_APP_TRIGGER_NAME }} to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.SAMPLE_APP_TRIGGER_NAME }}
          slot-name: "production"
          package: .
