name: wf_build_and_test
run-name: Build & Test

on:
  workflow_call:
    inputs:
      buildConfiguration:
        description: "Build Configuration"
        type: string
        default: "Release"

jobs:
  build-project:
    name: Build Project & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x
          dotnet-quality: ga
          cache: true
          cache-dependency-path: src/**/packages.lock.json

      - name: Create packages directory
        run: mkdir -p packages

      - name: Build IFTTT.NET project
        run: |
          dotnet restore
          dotnet build --no-restore --configuration ${{ inputs.buildConfiguration }} -p:GeneratePackageOnBuild=false

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ inputs.buildConfiguration }} --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          fail_below_min: true
          format: markdown
          hide_complexity: true
          output: both
          thresholds: "60 80"

      - name: Publish Code Coverage Report
        run: |
          echo "## Code coverage" >> $GITHUB_STEP_SUMMARY
          cat **code-coverage-results.md** >> $GITHUB_STEP_SUMMARY
