name: wf_nuget_publish
run-name: Publish NuGet Package

on:
  workflow_call:
    inputs:
      push_package_to_nuget:
        type: boolean
        default: false
      build_configuration:
        description: 'Build Configuration'
        type: string
        default: 'Release'
      version_suffix:
        description: 'Version Suffix'
        type: string
        default: ''
    secrets:
      nuget_api_key:
        description: 'NuGet API Key'
        required: true
    
env:
  PACKAGE_DIR_NAME: nupkgs
  PACKAGE_OUTPUT_PATH: $GITHUB_WORKSPACE/$PACKAGE_DIR_NAME/


jobs:
  prepare-package:
    name: Prepare Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: src

      - name: Create packages directory
        run: mkdir -p packages

      - name: Pack
        run: dotnet pack $GITHUB_WORKSPACE/src/InvvardDev.Ifttt.csproj --output $PACKAGE_DIR_NAME --configuration ${{ inputs.build_configuration }} -p:GeneratePackageOnBuild=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ${{ env.PACKAGE_OUTPUT_PATH }}

  publish-to-nuget:
    name: Publish Package to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ${{ env.PACKAGE_OUTPUT_PATH }}
          
      - name: Publish to NuGet
        if: inputs.push_package_to_nuget
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.* --api-key $api_key --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          api_key: ${{ secrets.nuget_api_key }}

  publish-to-github:
    name: Publish Package to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ${{ env.PACKAGE_OUTPUT_PATH }}
          
      - name: Publish to GitHub Packages
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_PATH }}/*.* --api-key $api_key --source https://nuget.pkg.github.com/InvvardDev/index.json --skip-duplicate --no-symbols
        env:
          api_key: ${{ secrets.GITHUB_TOKEN }}