name: wf_nuget_publish
run-name: Publish NuGet Package

on:
  workflow_call:
    inputs:
      push_package:
        type: boolean
        default: false
      build_configuration:
        description: 'Build Configuration'
        type: string
        default: 'Release'
      version_suffix:
        description: 'Version Suffix'
        type: string
        default: ''
    secrets:
      nuget_api_key:
        description: 'NuGet API Key'
        required: true
    
env:
  PACKAGE_PATH: nupkgs

jobs:
  prepare-package:
    name: Prepare Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: src

      - name: Create packages directory
        run: mkdir -p packages

      - name: Pack
        run: dotnet pack $GITHUB_WORKSPACE/src/InvvardDev.Ifttt.csproj --output $PACKAGE_PATH --configuration ${{ inputs.build_configuration }} -p:GeneratePackageOnBuild=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: $PACKAGE_PATH

  publish-to-nuget:
    name: Publish Package to NuGet
    runs-on: ubuntu-latest

    steps:
      - name: Publish to NuGet
        if: inputs.push_package
        run: dotnet nuget push $PACKAGE_PATH/*.* --api-key $api_key --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          api_key: ${{ secrets.nuget_api_key }}

  publish-to-github:
    name: Publish Package to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Publish to GitHub Packages
        run: dotnet nuget push ${{ env.package_path }}/*.* --api-key $api_key --source https://nuget.pkg.github.com/InvvardDev/index.json --skip-duplicate --no-symbols
        env:
          api_key: ${{ secrets.GITHUB_TOKEN }}