name: wf-samples-build
run-name: Build and deploy sample app

on:
  workflow_call:
    inputs:
      appDirName:
        description: "App directory name"
        type: string
        default: "sample-app"

env:
  APP_DIR_NAME: ${{ inputs.appDirName }}
  PUBLISH_DIR: ${{ github.workspace }}/publish

jobs:
  build:
    name: Build & Publish Trigger App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Samples directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: samples
          sparse-checkout-cone-mode: false

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga

      - name: Build & publish App
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}/
        working-directory: samples

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_DIR_NAME }}
          path: ${{ env.PUBLISH_DIR }}
