name: wf-samples-build
run-name: Build sample app

on:
  workflow_call:
    inputs:
      appName:
        description: "App name"
        type: string
        default: "sample-app"
      solutionFile:
        description: "Solution file"
        type: string
        default: "InvvardDev.Ifttt.Samples.sln"

jobs:
  build:
    name: Build & Publish ${{ inputs.appName }} app
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ inputs.appName }}
      PUBLISH_DIR: ${{ github.workspace }}/publish
      SOLUTION_FILE: ${{ inputs.solutionFile }}

    steps:
      - name: Checkout Samples directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            samples
            src
          sparse-checkout-cone-mode: false

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x
          dotnet-quality: ga

      - name: Build & Publish ${{ env.APP_NAME }}
        run: |
          dotnet restore ${{ env.SOLUTION_FILE }}
          dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore
          dotnet publish --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}/
        working-directory: samples

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.PUBLISH_DIR }}
