name: Workflow Tester
run-name: Workflow Tester

on:
  workflow_dispatch:
    inputs:
      tfAction:
        description: "Terraform action to run"
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan
  push:
    branches:
      - samples/*

env:
  TFPLAN_FILE_NAME: "tfplan"

jobs:
  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/wf-tf-plan.yaml
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  terraform-apply:
    name: Terraform Apply
    uses: ./.github/workflows/wf-tf-apply.yaml
    needs: terraform-plan
    if: ( github.event_name == 'push' || github.event.inputs.tfAction == 'apply') && needs.terraform-plan.outputs.tfplanExitCode == 2
    permissions:
      id-token: write
      contents: read
    secrets: inherit
