name: Workflow Tester
run-name: Workflow Tester

on:
  push:
    branches:
      - samples/*
  workflow_dispatch:

jobs:
  connect-to-azure:
    name: OICD Trigger App
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  run-azure-cmd:
    name: Run Azure CLI
    runs-on: ubuntu-latest
    needs: connect-to-azure
    permissions:
      id-token: write

    steps:
      - name: Run Azure CLI
        run: |
          az account show
