name: Workflow Tester
run-name: Workflow Tester

on:
  workflow_dispatch:

jobs:
  check_branch:
    name: Check branches
    runs-on: ubuntu-latest

    steps:
      - name: Evaluate ref values
        run: |
          echo "Base ref: ${{ github.base_ref }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "Ref type: ${{ github.ref_type }}"
          echo "Ref name glob: ${{ github.ref_name == 'feature/**' }}"
