name: wf_tf_destroy
run-name: TF Destroy

on:
  workflow_call:
    inputs:
      tfDirectory:
        description: "Terraform directory to run destroy on"
        type: string
        default: .github/samples-infra

jobs:
  tf-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment: development
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      WORKING_DIRECTORY: ${{ inputs.tfDirectory }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout Terraform
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.WORKING_DIRECTORY }}
          sparse-checkout-cone-mode: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve
