name: Workflow Tester
run-name: Workflow Tester

on:
  push:
    branches:
      - samples/*
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/wf-tf-plan.yaml
    permissions:
      id-token: write
      contents: read
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
