name: On Tag Push
run-name: Tag Push

on:
  push:
    tags: 
      - v0.[0-9]+.[0-9]+

jobs:
  github-example-tags:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src
            tests

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x

      - name: Create packages directory
        run: mkdir -p packages
            
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:GeneratePackageOnBuild=false

      - name: Set csproj version
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.4
        with:
          file: "**/src/*.csproj"
          version: bump-build

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
        