name: wf_tf_plan
run-name: TF Plan

on:
  workflow_call:
    inputs:
      tfDirectory:
        description: "Terraform directory to run plan on"
        type: string
        default: .github/samples-infra
      tfPlanFileName:
        description: "Terraform plan file name"
        type: string
        default: tfplan

    outputs:
      tfplanExitCode:
        description: "Terraform plan exit code"
        value: ${{ jobs.tf-plan.outputs.tfplanExitCode }}
jobs:
  tf-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: development
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      WORKING_DIRECTORY: ${{ inputs.tfDirectory }}
      TFPLAN_FILE_NAME: ${{ inputs.tfPlanFileName }}
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.WORKING_DIRECTORY }}
          sparse-checkout-cone-mode: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan -detailed-exitcode -no-color -out ${{ env.TFPLAN_FILE_NAME }} || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TFPLAN_FILE_NAME }}
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.TFPLAN_FILE_NAME }}

      - name: Publish Terraform Plan Summary
        id: tf-plan-summary
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color ${{ env.TFPLAN_FILE_NAME }})

          echo "## Terraform Plan Output" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          echo "$TERRAFORM_PLAN" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
