name: Workflow Tester
run-name: Workflow Tester

on:
  push:
    branches:
      - samples/*
  workflow_dispatch:

jobs:
  connect-to-azure:
    name: OICD Trigger App
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  terraform-plan:
    name: Terraform Plan
    uses: ./.github/workflows/wf-tf-plan.yaml
    permissions:
      id-token: write
      contents: read
